"""Write the Lambda zips' pinned requirements from uv.lock (issue #613).

build_function.sh used to hand pip the floors (``obstore>=0.8.2`` ...) and
build_layer.sh bare names (``fastparquet cramjam shapely`` ...), letting pip
resolve them and every transitive dep against PyPI at build time: the deployed
worker ran whatever was published that minute -- not what the test suite ran --
and the zip sizes moved with upstream releases. This script derives
``function-requirements.txt`` and ``layer-requirements.txt`` from the lock
instead: each root set mirrors what its build script installs, the closure is
walked over the lock's dependency graph, and the lines (``name==version ;
marker``) are taken verbatim from ``uv export`` so pip evaluates any
environment marker on the build host. The builds then install with
``--no-deps``: no resolution.

The layer file leaves out every name the ``lambda`` extra pins exactly:
build_layer.sh installs those itself from the extra (``lambda_pin``, PR #436;
numpy from source on arm64). A lock that disagrees with such a pin (stale)
needs no check here: ``uv export --locked`` refuses it.

Regenerate after a lock bump (tests/test_lambda_build.py fails until it is):

    uv run deployment/aws/lock_requirements.py
"""

import subprocess
import sys
import tomllib
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]

# Mirrors the package set build_function.sh installs into the zip.
FUNCTION_ROOTS = ("obstore", "zarr", "pydantic-zarr", "pyyaml")
# Mirrors build_layer.sh's installs (the lambda_pin'd names included, for their
# transitive deps; render() drops the names themselves). Deliberately not roots:
# h5coro (its boto3/earthaccess/requests/xarray deps are orchestrator-side, so
# the script installs it --no-deps), icechunk (its one dep, zarr, ships in the
# function zip) and mortie (floor-derived from pyproject, issue #322).
LAYER_ROOTS = (
    "pandas",
    "arro3-core",
    "fastparquet",
    "cramjam",
    "xarray",
    "h5netcdf",
    "h5py",
    "shapely",
    "pyproj",
    "odc-geo",
    "affine",
    "cachetools",
    "async-tiff",
    "h5coro-hidefix",
)


def closure(lock: dict, roots: tuple[str, ...]) -> set[str]:
    """Every lock package reachable from ``roots`` (markers ignored: pip applies them).

    An edge's ``extra = ["x"]`` also pulls the target's ``optional-dependencies.x``.
    A name the lock forks into several entries (``resolution-markers``) stops the
    walk: which entry the build host gets is not this script's call.
    """
    entries: dict[str, list[dict]] = {}
    for pkg in lock["package"]:
        entries.setdefault(pkg["name"], []).append(pkg)
    seen: set[str] = set()
    todo = [{"name": root} for root in roots]
    while todo:
        dep = todo.pop()
        name = dep["name"]
        if len(entries[name]) > 1:
            raise SystemExit(f"uv.lock forks {name} into {len(entries[name])} entries")
        pkg = entries[name][0]
        groups = {name: pkg.get("dependencies", [])}
        groups |= {f"{name}[{e}]": pkg["optional-dependencies"][e] for e in dep.get("extra", [])}
        for key, edges in groups.items():
            if key not in seen:
                seen.add(key)
                todo.extend(edges)
    return {key for key in seen if "[" not in key}


def lambda_extra_pins(pyproject: dict) -> frozenset[str]:
    """``{"numpy", ...}``: the names the extra pins exactly (one ``==``), which
    build_layer.sh installs on its own."""
    reqs = map(Requirement, pyproject["project"]["optional-dependencies"]["lambda"])
    return frozenset(
        canonicalize_name(r.name)
        for r in reqs
        if len(r.specifier) == 1 and next(iter(r.specifier)).operator == "=="
    )


def export(repo_root: Path) -> list[str]:
    """The locked requirement lines, one package each, as ``uv export`` prints them."""
    flags = (
        "--locked --no-dev --no-hashes --no-emit-project --extra lambda --format requirements-txt"
    )
    out = subprocess.run(
        ["uv", "export", "--project", str(repo_root), *flags.split()],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return [line for line in out.splitlines() if line and not line.startswith(("#", "-"))]


def render(
    lines: list[str], lock: dict, roots: tuple[str, ...], exclude: frozenset = frozenset()
) -> str:
    names = closure(lock, roots) - exclude
    kept = [line for line in lines if line.split("==")[0] in names]
    missing = names - {line.split("==")[0] for line in kept}
    if missing:
        raise SystemExit(f"uv export omitted lock packages {sorted(missing)}")
    header = f"# Generated by deployment/aws/lock_requirements.py from uv.lock -- do not edit.\n# Roots: {' '.join(roots)}\n"
    if exclude:
        header += f"# Without the lambda-extra pins build_layer.sh installs itself: {' '.join(sorted(exclude))}\n"
    return header + "\n".join(kept) + "\n"


def main(out_dir: Path) -> None:
    lock = tomllib.loads((REPO_ROOT / "uv.lock").read_text())
    pins = lambda_extra_pins(tomllib.loads((REPO_ROOT / "pyproject.toml").read_text()))
    lines = export(REPO_ROOT)
    (out_dir / "function-requirements.txt").write_text(render(lines, lock, FUNCTION_ROOTS))
    (out_dir / "layer-requirements.txt").write_text(render(lines, lock, LAYER_ROOTS, pins))


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else HERE)
