"""Write the Lambda function zip's pinned requirements from uv.lock (issue #613).

build_function.sh used to hand pip the floors (``obstore>=0.8.2`` ...) and let it
resolve them and every transitive dep against PyPI at build time, so the
deployed worker ran whatever was published that minute -- not what the test
suite ran -- and the function-zip size moved with upstream releases. This
script derives ``function-requirements.txt`` from the lock instead: the roots
below are the packages build_function.sh installs, the closure is walked over
the lock's dependency graph, and the lines (``name==version ; marker``) are
taken verbatim from ``uv export`` so pip evaluates any environment marker on
the build host. The build then installs with ``--no-deps``: no resolution.

Regenerate after a lock bump (tests/test_lambda_build.py fails until it is):

    uv run deployment/aws/lock_requirements.py
"""

import subprocess
import sys
import tomllib
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]

# Mirrors the package set build_function.sh installs into the zip.
FUNCTION_ROOTS = ("obstore", "zarr", "pydantic-zarr", "pyyaml")


def closure(lock: dict, roots: tuple[str, ...]) -> set[str]:
    """Every lock package reachable from ``roots`` (markers ignored: pip applies them)."""
    graph = {p["name"]: [d["name"] for d in p.get("dependencies", [])] for p in lock["package"]}
    seen: set[str] = set()
    todo = list(roots)
    while todo:
        name = todo.pop()
        if name not in seen:
            seen.add(name)
            todo.extend(graph[name])
    return seen


def export(repo_root: Path) -> list[str]:
    """The locked requirement lines, one package each, as ``uv export`` prints them."""
    flags = (
        "--frozen --no-dev --no-hashes --no-emit-project --extra lambda --format requirements-txt"
    )
    out = subprocess.run(
        ["uv", "export", "--project", str(repo_root), *flags.split()],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return [line for line in out.splitlines() if line and not line.startswith(("#", "-"))]


def render(repo_root: Path, roots: tuple[str, ...]) -> str:
    lock = tomllib.loads((repo_root / "uv.lock").read_text())
    names = closure(lock, roots)
    lines = [line for line in export(repo_root) if line.split("==")[0] in names]
    missing = names - {line.split("==")[0] for line in lines}
    if missing:
        raise SystemExit(f"uv export omitted lock packages {sorted(missing)}")
    header = f"# Generated by deployment/aws/lock_requirements.py from uv.lock -- do not edit.\n# Roots: {' '.join(roots)}\n"
    return header + "\n".join(lines) + "\n"


def main(out_dir: Path) -> None:
    (out_dir / "function-requirements.txt").write_text(render(REPO_ROOT, FUNCTION_ROOTS))


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else HERE)
